# Generated by Django 6.0.3 on 2026-03-06 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_name', models.CharField(default='# 91 VRS Cafe', max_length=200)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=30)),
                ('address', models.CharField(default='123 Coffee Street, Bengaluru', max_length=300)),
                ('gst', models.CharField(default='29XXXXX1234X1ZX', max_length=30)),
                ('tax_rate', models.FloatField(default=5.0, help_text='Tax percentage applied to bills')),
                ('total_tables', models.PositiveSmallIntegerField(default=12)),
                ('opening_time', models.TimeField(default='09:00')),
                ('closing_time', models.TimeField(default='23:00')),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('footer_message', models.CharField(default='Thank you for visiting # 91 VRS Cafe!', max_length=300)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('instagram_url', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Cafe Settings',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.PositiveSmallIntegerField(help_text='Table number shown to customers', unique=True)),
                ('capacity', models.PositiveSmallIntegerField(default=4)),
                ('location', models.CharField(blank=True, help_text='e.g. "Window", "Terrace", "Main Hall"', max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('qr_code_url', models.CharField(blank=True, help_text='URL to the table QR code image', max_length=500)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(help_text='Promo code entered by customer', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or fixed INR amount', max_digits=8)),
                ('min_order_amount', models.PositiveIntegerField(default=0, help_text='Minimum subtotal required for the code to apply')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited uses', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='cafe_discou_code_b39716_idx'), models.Index(fields=['valid_until'], name='cafe_discou_valid_u_60c7d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='KitchenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('table_num', models.PositiveSmallIntegerField()),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('special_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('estimated_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status'], name='cafe_kitche_status_e15c9a_idx'), models.Index(fields=['created_at'], name='cafe_kitche_created_9782a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='KitchenOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('price', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='cafe.kitchenorder')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(help_text='Price in INR (₹)')),
                ('category', models.CharField(choices=[('coffee', 'Coffee'), ('burgers', 'Burgers'), ('pizza', 'Pizza'), ('mains', 'Mains'), ('desserts', 'Desserts'), ('drinks', 'Drinks'), ('snacks', 'Snacks')], max_length=50)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('emoji', models.CharField(default='🍽️', max_length=10)),
                ('is_veg', models.BooleanField(default=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('trending', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('preparation_time_minutes', models.PositiveSmallIntegerField(default=10)),
                ('allergens', models.CharField(blank=True, help_text='Comma-separated list, e.g. "gluten, dairy"', max_length=300)),
                ('serving_size', models.CharField(blank=True, help_text='e.g. "300ml" or "250g"', max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower values appear first in listings')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['category'], name='cafe_menuit_categor_303733_idx'), models.Index(fields=['in_stock'], name='cafe_menuit_in_stoc_4eb10d_idx'), models.Index(fields=['trending'], name='cafe_menuit_trendin_246138_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('table_num', models.PositiveSmallIntegerField()),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('special_instructions', models.TextField(blank=True)),
                ('items_json', models.JSONField(default=list)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('discount_amount', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI')], default='cash', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-closed_at'],
                'indexes': [models.Index(fields=['closed_at'], name='cafe_salesr_closed__3ee2e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('table_num', models.PositiveSmallIntegerField()),
                ('overall_rating', models.PositiveSmallIntegerField(help_text='1–5 stars')),
                ('food_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('service_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('session_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='cafe.salesrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('table_num', models.PositiveSmallIntegerField(unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('special_instructions', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('bill_printed', models.BooleanField(default=False)),
                ('session_type', models.CharField(choices=[('dine_in', 'Dine-In'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='dine_in', max_length=20)),
                ('discount_code', models.CharField(blank=True, max_length=50)),
                ('discount_amount', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['table_num'],
                'indexes': [models.Index(fields=['table_num'], name='cafe_tables_table_n_2e945d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('party_size', models.PositiveSmallIntegerField()),
                ('reserved_date', models.DateField()),
                ('reserved_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('seated', 'Seated'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='cafe.table')),
            ],
            options={
                'ordering': ['reserved_date', 'reserved_time'],
                'indexes': [models.Index(fields=['reserved_date'], name='cafe_reserv_reserve_959a4d_idx'), models.Index(fields=['status'], name='cafe_reserv_status_aed449_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('price', models.PositiveIntegerField(help_text='Price snapshot at order time')),
                ('notes', models.CharField(blank=True, help_text='Item-level special request', max_length=200)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafe.menuitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_items', to='cafe.tablesession')),
            ],
            options={
                'unique_together': {('session', 'menu_item')},
            },
        ),
    ]
