# Generated by Django 6.0.3 on 2026-03-06 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_name', models.CharField(default='# 91 VRS Cafe', max_length=200)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=30)),
                ('address', models.CharField(default='123 Coffee Street, Bengaluru', max_length=300)),
                ('gst', models.CharField(default='29XXXXX1234X1ZX', max_length=30)),
                ('tax_rate', models.FloatField(default=5.0, help_text='Tax percentage applied to bills')),
                ('total_tables', models.PositiveSmallIntegerField(default=12)),
            ],
            options={
                'verbose_name_plural': 'Cafe Settings',
            },
        ),
        migrations.CreateModel(
            name='KitchenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_num', models.PositiveSmallIntegerField()),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('special_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(help_text='Price in INR (₹)')),
                ('category', models.CharField(choices=[('coffee', 'Coffee'), ('burgers', 'Burgers'), ('pizza', 'Pizza'), ('mains', 'Mains'), ('desserts', 'Desserts'), ('drinks', 'Drinks'), ('snacks', 'Snacks')], max_length=50)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('emoji', models.CharField(default='🍽️', max_length=10)),
                ('is_veg', models.BooleanField(default=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('trending', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_num', models.PositiveSmallIntegerField()),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('special_instructions', models.TextField(blank=True)),
                ('items_json', models.JSONField(default=list)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-closed_at'],
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_num', models.PositiveSmallIntegerField(unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('special_instructions', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('bill_printed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['table_num'],
            },
        ),
        migrations.CreateModel(
            name='KitchenOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='cafe.kitchenorder')),
            ],
        ),
        migrations.CreateModel(
            name='SessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('price', models.PositiveIntegerField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafe.menuitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_items', to='cafe.tablesession')),
            ],
            options={
                'unique_together': {('session', 'menu_item')},
            },
        ),
    ]
