# Generated by Django 6.0.3 on 2026-03-06 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('table_num', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('kitchen', 'Kitchen'), ('cashier', 'Cashier')], default='kitchen', max_length=20)),
            ],
            options={
                'verbose_name': 'Staff Profile',
            },
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Customer IP captured at order time', null=True),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Customer IP for anonymous tracking', null=True),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['ip_address'], name='cafe_salesr_ip_addr_abf00f_idx'),
        ),
        migrations.AddField(
            model_name='customervisit',
            name='sales_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_visits', to='cafe.salesrecord'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunSQL(
            sql="""
                CREATE VIEW IF NOT EXISTS cafe_daily_sales AS
                SELECT
                    date(closed_at)  AS sale_date,
                    COUNT(*)         AS orders,
                    SUM(total)       AS revenue,
                    AVG(total)       AS avg_order,
                    SUM(discount_amount) AS total_discounts
                FROM cafe_salesrecord
                GROUP BY date(closed_at);

                CREATE VIEW IF NOT EXISTS cafe_customer_ip_summary AS
                SELECT
                    ip_address,
                    COUNT(*)   AS visits,
                    SUM(total) AS lifetime_spend,
                    MAX(closed_at) AS last_visit
                FROM cafe_salesrecord
                WHERE ip_address IS NOT NULL
                GROUP BY ip_address;
            """,
            reverse_sql="""
                DROP VIEW IF EXISTS cafe_daily_sales;
                DROP VIEW IF EXISTS cafe_customer_ip_summary;
            """,
        ),
    ]
