# Generated by Django 6.0.3 on 2026-03-06 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('preferred_name', models.CharField(blank=True, help_text='Name set by customer on last order', max_length=200)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('device_info', models.CharField(blank=True, help_text='User-Agent string of last visit', max_length=500)),
            ],
            options={
                'verbose_name': 'Customer Visit',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin / Manager'), ('kitchen', 'Kitchen Staff'), ('waiter', 'Waiter / Front-of-house')], default='waiter', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('profile_picture_url', models.URLField(blank=True, max_length=500)),
                ('is_on_duty', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Profile',
            },
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Customer IP captured at order time', null=True),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Customer IP for anonymous tracking', null=True),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['ip_address'], name='cafe_salesr_ip_addr_abf00f_idx'),
        ),
        migrations.AddIndex(
            model_name='customervisit',
            index=models.Index(fields=['ip_address'], name='cafe_custom_ip_addr_69947e_idx'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunSQL(
            sql="""
CREATE VIEW IF NOT EXISTS v_daily_revenue AS
SELECT
    date(closed_at)        AS sale_date,
    COUNT(*)               AS order_count,
    SUM(total)             AS total_revenue,
    AVG(total)             AS avg_order_value,
    SUM(discount_amount)   AS total_discounts
FROM cafe_salesrecord
GROUP BY date(closed_at)
ORDER BY sale_date DESC;

CREATE VIEW IF NOT EXISTS v_popular_items AS
SELECT
    json_extract(item.value, '$.name')              AS item_name,
    json_extract(item.value, '$.category')          AS category,
    SUM(json_extract(item.value, '$.qty'))          AS total_qty_sold,
    SUM(
      json_extract(item.value, '$.price') *
      json_extract(item.value, '$.qty')
    )                                               AS total_revenue
FROM cafe_salesrecord,
     json_each(cafe_salesrecord.items_json) AS item
GROUP BY json_extract(item.value, '$.name')
ORDER BY total_qty_sold DESC;

CREATE VIEW IF NOT EXISTS v_table_status AS
SELECT
    t.number,
    t.capacity,
    t.location,
    t.status                       AS table_status,
    s.customer_name,
    s.start_time                   AS session_start,
    ROUND(
      (julianday('now') - julianday(s.start_time)) * 24 * 60
    )                              AS minutes_occupied
FROM cafe_table t
LEFT JOIN cafe_tablesession s ON s.table_num = t.number
ORDER BY t.number;
""",
            reverse_sql="""
DROP VIEW IF EXISTS v_table_status;
DROP VIEW IF EXISTS v_popular_items;
DROP VIEW IF EXISTS v_daily_revenue;
""",
        ),
    ]
