# Generated by Django 6.0.3 on 2026-03-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_customer_auth_sql_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_code_data',
            field=models.TextField(blank=True, help_text='Base64-encoded PNG of the QR code (data URI ready for <img src>)'),
        ),
        migrations.AlterField(
            model_name='cafesettings',
            name='cafe_name',
            field=models.CharField(default='SK Cafe', max_length=200),
        ),
        migrations.AlterField(
            model_name='cafesettings',
            name='footer_message',
            field=models.CharField(default='Thank you for visiting SK Cafe!', max_length=300),
        ),
    ]
